EVALUATE
VAR DiasHistorico = 730
VAR DataFim = TODAY()
VAR DataInicio = DataFim - DiasHistorico
VAR Periodo =
    FILTER(
        ALL('dCalendario'[Data]),
        'dCalendario'[Data] >= DataInicio
            && 'dCalendario'[Data] <= DataFim
    )
RETURN
FILTER(
    SUMMARIZECOLUMNS(
        'CADEMP'[ANOMEFANTASIA],
        'PRODUTOS'[ACODPRODUTO],
        'dCalendario'[Data],
        Periodo,
        "QtdVenda", CALCULATE([Quantidade Vendida Produto], KEEPFILTERS('NOTAS'[Tipo Movimentação] = "Venda Direta"))
    ),
    [QtdVenda] <> 0
)
ORDER BY 'CADEMP'[ANOMEFANTASIA], 'PRODUTOS'[ACODPRODUTO], 'dCalendario'[Data]
